### ISSUE TITLE
Yay!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-constanza-sosa#1]
Good job @constanza-sosa,

- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document

The exercise is more than ok, but you must be careful with the counter function that you assign to the `growingCounter` constant, that you don't really need.

You can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button, and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that clears the field, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

**Comment by constanza-sosa** [comment]
I did:

- [X] Add 'use strict'
- [X] Add new feedback when the number is bigger than 100 or smaller than 0.
- [X] Manage when the user hits the button, and the input is empty. --> Doesn't count, doesn't push to array and clue changes. 
- [X] Make the input work when hitting the enter key.
- [X] Add a reset button that clears the field, the counter, writes the initial feedback and generates a new random number to play again!
- [X] Add a "Show the "randomNumber button"
- [X] Add css
- [X] Add a modal to enter name
- [X] Show numbers introduced by painting pushing number to array and paint the list
